#开发环境配置
server:
  # 端口号
  port: 8080
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
  http2:
    enabled: true


#sping配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #配置文件使用
  profiles:
    active:
      - druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml # 扫描mybatis的实现dao接口*.xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.natane.**.entity
logging:
  level:
    com.natane: debug
    org.springframework: warn