spring:
  application:
    # 应用名称
    name: natane
  profiles:
    active:
      - druid
server:
  # 端口号
  port: 8080
  http2:
    enabled: true

bean-searcher:
  sql:
    default-mapping:
      underline-case: true
    #慢sql(ms)默认为 500
    slow-sql-threshold: 1000
    #方言
    dialect: MySQL

